#!/usr/bin/env python3
"""Regenerate the bundled Unicode 16.0 names using Python's matching database."""
import pathlib
import unicodedata as u
assert u.unidata_version == '16.0.0', 'Use Python with Unicode 16.0.0'
out = pathlib.Path(__file__).resolve().parents[1] / 'vendor/unicode/names.inc'
with out.open('w') as f:
    f.write('// Generated by tools/generate_unicode.py; Unicode 16.0.0.\n')
    for cp in range(0x110000):
        name = u.name(chr(cp), '')
        if name:
            f.write(f'{{0x{cp:X}, "{name}"}},\n')
