#!/usr/bin/env python3
"""Regenerate compact Unicode 16.0 names using Python's matching database."""
import pathlib
import unicodedata as u
assert u.unidata_version == '16.0.0', 'Use Python with Unicode 16.0.0'
out = pathlib.Path(__file__).resolve().parents[1] / 'vendor/unicode/names.inc'
blocks, current, size, entries = [], [], 0, []
for cp in range(0x110000):
    name = u.name(chr(cp), '')
    if not name:
        continue
    if size + len(name) + 1 > 32000:
        blocks.append(current)
        current, size = [], 0
    entries.append((cp, len(blocks), size))
    current.append(name)
    size += len(name) + 1
blocks.append(current)
with out.open('w') as f:
    f.write('// Generated by tools/generate_unicode.py; Unicode 16.0.0.\n')
    f.write('// Small string blocks avoid MSVC object-section and string-size limits.\n')
    for i, block in enumerate(blocks):
        f.write(f'inline constexpr char name_block_{i}[] =\n')
        for name in block:
            f.write('"' + name + '\\0"\n')
        f.write(';\n')
    f.write('inline constexpr const char* name_blocks[] = {\n')
    for i in range(len(blocks)):
        f.write(f'name_block_{i},\n')
    f.write('};\ninline constexpr Name names[] = {\n')
    for cp, block, offset in entries:
        f.write(f'{{0x{cp:X}, {block}, {offset}}},\n')
    f.write('};\n')

# Preview-only classification; clipboard payloads always remain unchanged.
ranges = []
for cp in range(0x110000):
    category = u.category(chr(cp))
    kind = 1 if category[0] == 'Z' or category in ('Cc', 'Cf', 'Cs') or cp in (0x115f, 0x1160, 0x2800, 0x3164, 0xffa0) or 0xfe00 <= cp <= 0xfe0f or 0xe0100 <= cp <= 0xe01ef else 2 if category[0] == 'M' else 0
    if not kind:
        continue
    if ranges and ranges[-1][1] + 1 == cp and ranges[-1][2] == kind:
        ranges[-1][1] = cp
    else:
        ranges.append([cp, cp, kind])
with out.with_name('preview.inc').open('w') as f:
    f.write('// Generated by tools/generate_unicode.py; Unicode 16.0.0.\n')
    f.write('inline constexpr PreviewRange preview_ranges[] = {\n')
    for first, last, kind in ranges:
        f.write(f'{{0x{first:X}, 0x{last:X}, {kind}}},\n')
    f.write('};\n')
